### ISSUE TITLE
[wish] option for eager streaming

### ISSUE THREAD

**Issue by astrowalker** [blueimp/mjpeg-server#2]
It is a great program, thank you very much.

"[it] starts the given recording command when the first HTTP client connects:"

Would it be possible to introduce an option for controlling this behavior. I found problematic a bit, when the data feed is pushed through named pipe (Windows), I need to wait for connection being established (i.e. ffmpeg) and ffmpeg does not start because there are no clients. So my app kind of freezes just waiting for a client.

Of course there is an easy workaround, simply start client, and then main app, but having such option would allow to start both parties in any order.

**Comment by blueimp** [comment]
Thanks for your request @astrowalker.

I wasn't sure if your use case is enough reason to warrant the addition of such an option, but given that FFmpeg supports writing to multiple outputs, this could have other benefits as well.

**Comment by blueimp** [comment]
Hi @astrowalker, I just release a new version ([v1.3.0](https://github.com/blueimp/mjpeg-server/releases/tag/v1.3.0)) that supports the new `-d` option to enable direct start of the recording program:
https://github.com/blueimp/mjpeg-server#options
