### ISSUE TITLE
Error fork/exec : no such file or directory

### ISSUE THREAD

**Issue by surajshah** [blueimp/mjpeg-server#3]
I have installed mjpeg-server on Ubuntu Focal Fossa. When i call the url from outside i see these logs:

sudo ./mjpeg-server -d
2020/10/25 18:38:26 fork/exec : no such file or directory
{"ID":"1","Time":"2020-10-25T17:38:38.697133947Z","RemoteIP":"yyyyyyyy","Method":"GET","Host":"xxxxxxxxxx:9000","RequestURI":"/","Referrer":"","UserAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36","ForwardedFor":"","ForwardedHost":"","ForwardedProto":""}
{"ID":"1","Time":"2020-10-25T17:38:38.697452011Z","Registered":true,"NumClients":1}

What could be the cause?

Thanks

**Comment by blueimp** [comment]
Hi @surajshah,

the error looks like you're not passing a command argument to provide the MJPEG stream:
https://github.com/blueimp/mjpeg-server#usage

The most common usage is using ffmpeg for screen recordings as explained here:
https://github.com/blueimp/mjpeg-server#linux

**Comment by surajshah** [comment]
Hi, @blueimp, thank you for the suggestion, I will try this out and update you.

**Comment by surajshah** [comment]
It works fine:

Here is a script I made to pass some params directly (in Linux):


`#!/bin/sh    
  
export  DISPLAYSIZE=$(xdpyinfo | awk '/dimensions:/ { print $2; exit }')
echo $DISPLAY $DISPLAYSIZE
./mjpeg-server -- ffmpeg   -loglevel fatal   -probesize 32   -fpsprobesize 0   -analyzeduration 0   -fflags nobuffer   -f x11grab   -r 15   -video_size "$DISPLAYSIZE" -i "$DISPLAY" -f mpjpeg   -q 2   -`

**Comment by blueimp** [comment]
Thanks for posting your solution! :)
